### ISSUE TITLE
bs-platform 5.0.4 is not playing well with this extension

### ISSUE THREAD

**Issue by sync** [jaredly/reason-language-server#275] opened 2019-04-30 05:09 UTC
How to reproduce it:
- add bs-platform 5.0.4 and open a .re file with Reason ppx 3 inside vscode.

![Screen_Shot_2019-04-30_at_10 12 09_am](https://user-images.githubusercontent.com/21725/56941737-d1f0ee80-6b59-11e9-9d5d-2a8bb6c703cd.png)

Got this reply in discord:

```
@anthony ah, check  this blog post: https://bucklescript.github.io/blog/2019/04/22/release-5-0-4 , it should be easy to fix (cc @jaredly )
architecture changes in bs-platform v5.0.4 and v6.0.1 · BuckleScript
We are going to make releases of bs-platform@5.0.4 and bs-platform@6.0.1, this release mostly contains bug fixes.
if you see the command line, the ' quote is misplaced
```

**Comment by briangorman** [comment] 2019-05-01 17:02
I see this with jsx 2 as well

```sh: /Users/brian_gorman/code/REDACTED/node_modules/bs-platform/lib/bsppx.exe -bs-jsx 2: No such file or directory
File "", line 1:
Error: Error while running external preprocessor
Command line: '/Users/brian_gorman/code/REDACTED/node_modules/bs-platform/lib/bsppx.exe -bs-jsx 2' '/var/folders/qs/tzcsbc9s5vb3mbvd2wnrdcgr0000gn/T/camlppxe2ea91' '/var/folders/qs/tzcsbc9s5vb3mbvd2wnrdcgr0000gn/T/camlppx380c03'```

**Comment by thangngoc89** [comment] 2019-05-01 17:03
@briangorman there is no actual jsx2 or jsx3. It's the same ppx that works based on your config

**Comment by MoOx** [comment] 2019-05-02 08:36
@thangngoc89 this error just popped up with a recent bs-platform release (and that's annoying)

Not sure what we can do about it. poke @bobzhang

**Comment by thangngoc89** [comment] 2019-05-02 13:51
@MoOx bsppx.exe was removed. RLS simply needs to not calling that binary

**Comment by MoOx** [comment] 2019-05-02 13:52
Looks like an unexpected breaking change.
So you are telling me we can just drop the call in RLS & it will be good?

**Comment by thangngoc89** [comment] 2019-05-02 13:53
@MoOx yep. just drop it

**Comment by phated** [comment] 2019-05-02 17:05
The PPX is now bundled with bsb (or is it bsc? 😛) to speed up performance, and improve overall interaction and maintenance of it within bsb (it's currently copied over from the reason-react repository).  We also needed to make this change so the new architecture of bucklescript would allow us to properly build the reasonml playground.

**Comment by bobzhang** [comment] 2019-05-03 01:52
if you read the log, it is a misplaced quote, should be easy to fix.

```
'/path/to/bsppx.exe -bs-jsx 3' file
```
```
'/path/to/bsppx.exe' -bs-jsx 3 file
```

**Comment by sync** [comment] 2019-05-04 01:20
ok so by changing `examples/example-react/package.json` to `"bs-platform": "^5.0.4"` and then running:

```sh
esy exec-command --include-build-env cp _build/install/default/bin/ExamplesTests ExamplesTests.exe
./ExamplesTests.exe
```

i can reproduce the error:

```
## Tests failed! ##
- Failed to get compilation info for file:///Users/anthonymittaz/Projects/Reason/reason-language-server/examples/example-react/__tests__/example_tests.re : sh: /Users/anthonymittaz/Projects/Reason/reason-language-server/examples/example-react/node_modules/bs-platform/lib/bsppx.exe -bs-jsx 2: No such file or directory
File "", line 1:
Error: Error while running external preprocessor
Command line: '/Users/anthonymittaz/Projects/Reason/reason-language-server/examples/example-react/node_modules/bs-platform/lib/bsppx.exe -bs-jsx 2' '/var/folders/12/3py3x7j151s4nsbxns4jbs7w0000gn/T/camlppx705a9a' '/var/folders/12/3py3x7j151s4nsbxns4jbs7w0000gn/T/camlppx47ecc9'
```

Next step is to fix it :-)

**Comment by maseb** [comment] 2019-05-05 01:16
Hit this issue today while following the getting started docs. If I manually tweak the quote in the bsb-generated `.merlin` file, my RLS issues go away, so I'm assuming this is the offending line, rather than something in RLS itself...?

https://github.com/BuckleScript/bucklescript/commit/071bad06b4ef6664645b312ef3cdc648d311b815#diff-67c6fd1744cb0d1af83dc9d67cb71c8cR135

**Comment by bobzhang** [comment] 2019-05-05 01:21
@maseb can you post the diff of how you tweaked the .merlin? That would be very helpful 
It’s a bit surprising to me since RLS is something in parallel to merlin

**Comment by maseb** [comment] 2019-05-05 01:33
@bobzhang 

This was simply following this instruction:

https://reasonml.github.io/reason-react/docs/en/installation

Error I got from VSCode:

```
sh: /Users/mase/dev/impact/my-react-app/node_modules/bs-platform/lib/bsppx.exe -bs-jsx 3: No such file or directory
File "", line 1:
Error: Error while running external preprocessor
Command line: '/Users/mase/dev/impact/my-react-app/node_modules/bs-platform/lib/bsppx.exe -bs-jsx 3' '/var/folders/dk/cn07d7_j49s3ccg01hcqrqpc0000gn/T/camlppx162d1a' '/var/folders/dk/cn07d7_j49s3ccg01hcqrqpc0000gn/T/camlppx185426'
```

Change I made:

```diff
4c4
< FLG -ppx '/Users/mase/opt/nodenv/versions/11.1.0/lib/node_modules/bs-platform/lib/bsppx.exe -bs-jsx 3'
---
> FLG -ppx '/Users/mase/dev/impact/my-react-app/node_modules/bs-platform/lib/bsppx.exe' -bs-jsx 3

```

After making that change and reloading VSCode, it works.

**Comment by bobzhang** [comment] 2019-05-05 05:45
Can anyone confirm that https://github.com/BuckleScript/bucklescript/pull/3544 fixes this? If so, I will make a release soon.

Sorry for this break. Such breakage is hard to detect on CI, I wish that the community can help report such issues earlier so that it would be caught earlier

**Comment by sync** [comment] 2019-05-05 06:07
Will be in front of a computer in one hour and should be able to try it then.

**Comment by maseb** [comment] 2019-05-05 06:26
@bobzhang I built https://github.com/BuckleScript/bucklescript/pull/3544 and created a new project from scratch, following https://reasonml.github.io/reason-react/docs/en/installation - all good for me now in RLS/vscode. 

Aside:

While this fixes the symptom, I wonder there isn't a deeper issue with how RLS makes a special effort to escape ppx flags. The logic it uses for parsing and splitting the `.merlin` doesn't work well when the value there is already quoted:

https://github.com/jaredly/reason-language-server/blob/master/src/analyze/Packages.re#L10

**Comment by bobzhang** [comment] 2019-05-05 06:49
Just in case, such change should be good with merlin too, correct?

**Comment by sync** [comment] 2019-05-05 09:14
can confirm @maseb fix is working

**Comment by thangngoc89** [comment] 2019-05-05 09:54
@bobzhang RLS has its own diagnostic engine but it uses .merlin files for build information

**Comment by bobzhang** [comment] 2019-05-05 10:22
@maseb after some thoughts, I tend to agree with you: this is not a bug from bsb side, it may be a mis-interpretation of merlin format. If we made changes on our side, it may break merlin in some way.
cc @jaredly , could it be fixed on RLS side?

**Comment by IwanKaramazow** [comment] 2019-05-05 13:52
@bobzhang I'll fix the problem on the RLS side. Shouldn't be too hard.

**Comment by arjun-menon** [comment] 2019-05-11 12:25
I can confirm @maseb's fix is working as well. Thanks, @maseb!

**Comment by donut** [comment] 2019-05-13 16:58
I created a messy fork of bs-platform with @maseb's fix to make it easy to add as a package while we wait for RLS to be updated: https://github.com/RightThisMinute/bucklescript/

**Comment by IwanKaramazow** [comment] 2019-05-15 17:02
Sorry for the delay, lost track of the issue. PR with a fix is ready here: https://github.com/jaredly/reason-language-server/pull/281

**Closed** 2019-05-16 17:49 UTC
