### ISSUE TITLE
Links in comments will result in comment terminator not parsed, thus highlighting the remaining lines as comments

### ISSUE THREAD

**Issue by ambientlight** [jaredly/reason-language-server#241] opened 2019-02-06 05:50 UTC
Steps to reproduce:
1. clone https://github.com/SentiaAnalytics/bs-css.git
2. in vsCode, open `src/Css.re` on line 1328. Notice:

<img width="1126" alt="screen shot 2019-02-06 at 1 50 22 pm" src="https://user-images.githubusercontent.com/14032724/52322970-2c285a80-2a16-11e9-8493-a249adb1702a.png">

**Comment by mlms13** [comment] 2019-02-11 17:40
Does the syntax highlighting code come from upstream? I noticed the same issue somewhere else (possibly Reason syntax highlighting on Github?)

**Comment by jaredly** [comment] 2019-04-13 00:42
Yeah, I've just copied it from elsewhere

**Comment by nireno** [comment] 2019-04-17 19:47
I assume something's getting confused with the single-line comment `//` in `http://`. If I close the multi-line comment on a new line the problem goes away.

**Comment by hartmut27** [comment] 2020-04-04 17:23
I've tested the issue on different ways with the mentioned git clone source code and the commentaries, 
but I cannot reproduce.
Eventually the bug is no bug any more...

**Comment by ambientlight** [comment] 2020-04-04 17:25
should it be closed in such case?

**Comment by hartmut27** [comment] 2020-04-05 13:19
Yes, imho please close the issue

**Closed** 2020-04-06 11:25 UTC
Labels: bug, syntax highlighting
